apiVersion: v1 
kind: PersistentVolume
metadata: 
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOne
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-096ba58344c8fe215